### ISSUE TITLE
cf delete behaves oddly with multiple targets

### ISSUE THREAD

**Issue by andypiper** [cloudfoundry-attic/cf#19] opened 2013-06-25 13:00 UTC
When deleting two apps, one of which has bound services, some strange things can happen.

```
~  cf delete spring-stocks lleksah
Really delete spring-stocks?> y

Deleting spring-stocks... OK

Really delete lleksah?> y

Deleting lleksah... OK

Delete orphaned service stocks-rabbit?> n
Really delete lleksah?> y

Deleting lleksah... FAILED
CFoundry::AppNotFound: 100004: The app name could not be found: f043b700-0df1-41f4-938a-21d615cfc42b
For more information, see ~/.cf/crash
```

To clarify:
- delete app1 (with bound service), app2
- confirm deletion of both apps -> deleted
- ignore message about orphaned service
- -> repeated attempt to delete app2 -> failure

**Comment by tlang** [comment] 2013-06-25 23:53
Bug filed and prioritized, thanks.

**Comment by stubbornella** [comment] 2013-07-01 17:34
We weren't able to reproduce this bug with the latest version of cf. It looks like it might be a soft-delete bug. Can you try updating cf and let us know if you still see this behavior?

If you can provide more detailed steps to reproduce or detailed logs of the failure (e.g. the content of ~/.cf/crash file) we'd be happy to take another look. Thanks!

**Comment by cf-frontend** [comment] 2013-07-17 20:54
Closing for now, if you are still seeing this with the latest cf, please reopen it.

**Closed as completed by cf-frontend** 2013-07-17 20:54 UTC
